# -*- coding: utf-8 -*-
"""lesson5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMzvGXEMRT36RZrYIb1UxChVTj9OyKD5
"""

a = (1,2,3,4,56,6,5)

x = 0
for i in a:
  x += 1
  print(f"{x}")
  if i == 5:
    print("Знайшов")
    break

set_example = {1,1,1,2,3,4,5}

4 in set_example

a = {
    'key': 'value',
    1: 44,
    1: 42,
}

a_d = dict(name=44, value=55)

a_d

l = [
    (0.2, 0.4),
    (0.4, 0.6),
]

def func_example():
  return (0, 4, 5)



a = [1,2,3,4,5,6,7]

print(a)

a.append(8)

print(a)

a.remove(6)

a

a.remove(7)

a

a.insert(1, 42)

a

a.insert(6, 23)

a

a.sort(reverse=True)

t = (1,2,3,3,3,3,34,5,65)

t.index(65)

(1,2,3,4) + (5,6,7,8)

a = {1,2,3,4,5,6,7}

a.add(42)

a

a.remove(42)

a

b = {5,6,7,8,9}

a.union(b)

a.symmetric_difference(b)

a.intersection(b)

a = {"a", "b", "c"}

c = {"a", "b", "c"}

a.symmetric_difference(c)





d = {'a': 1, 'b': 2, 'c': 4}

d

d.get('a', None)

del d['a']

d.get('a', 'None')

a = [1,2,3,4,5]

for key in d:
  print(f"key: {key}; value={d[key]}")

for key in d.keys():
  print(f"key: {key}; value={d[key]}")

for value in d.values():
  print(f"value: {value}")

for key, value in d.items():
  print(f"key: {key}; value: {value}")

"""#Відфільтруйте унікальні не-спам email-адреси зі списку email-ів."""

emails = ["friend@example.com", "spam@example.com", "friend@example.com"]
spam_list = {"spam@example.com"}

emails = set(emails)

emails.symmetric_difference(spam_list)

"""# Створіть список покупок, де кожна покупка представлена словником, що містить назву товару, кількість та ціну за одиницю. Розрахуйте загальну вартість покупок."""

shopping_list = [
    {"name": "milk", "quantity": 2, "price": 30},
    {"name": "bread", "quantity": 1, "price": 20},
    {"name": "eggs", "quantity": 12, "price": 50}
]

shopping_sum = 0

for element in shopping_list:
  value = element['price'] * element['quantity']
  shopping_sum += value

sum([element['price'] * element['quantity'] for element in shopping_list])

"""#Підрахуйте відповіді за категоріями від учасників опитування."""

survey_responses = [
    {"name": "Alice", "response": "Yes"},
    {"name": "Bob", "response": "No"},
    {"name": "Charlie", "response": "Yes"},
    {"name": "Valeria", "response": "No"},
    {"name": "Dima", "response": "No"},
    {"name": "Smit", "response": "No"},
]

yes_count = 0
no_count = 0
for element in survey_responses:
  if element['response'] == 'Yes':
    yes_count += 1
  if element['response'] == 'No':
    no_count += 1
  else:
    continue

print(yes_count)
print(no_count)

yes_count = 0
no_count = 0
for element in {1,2,3,4,5}:
  no_count += 1

"""#Визначення переможця змагань"""

results = [
    ("Alice", "B", 9),
    ("Bob", "C", 12),
    ("Charlie", "D", 11),
    ("Dima", "B", 1),
]

winner_name = ''
max_result = 0

for name, surname, score in results:
  print(f"{name} {surname} {score}")
  if score > max_result:
    max_result = score
    winner_name = name + " " + surname

print(winner_name)

"""#Розрахунок середнього балу студентів"""

students_grades = {
    "Alice": [4, 5, 3, 4, 7, 89],
    "Bob": [5, 5, 4, 5, 33],
    "Charlie": [3, 4, 2, 3]
}

for student_name, student_grades in students_grades.items():
  grade_avg = sum(student_grades) / len(student_grades)
  print(f"Student name: {student_name}; student grade: {grade_avg}")

students_grades['Alice']

for key, valua in students_grades.items():
  print(key)
  print(valua)

